/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuInterface;

/**
 *
 * @author Bryan Keihl
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        interfaceMenuBar = new javax.swing.JMenuBar();
        systemMenu = new javax.swing.JMenu();
        creditsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        registryMenu = new javax.swing.JMenu();
        materialMenu = new javax.swing.JMenu();
        bookMenuItem = new javax.swing.JMenuItem();
        audioVisualMenuItem = new javax.swing.JMenuItem();
        studentMenuItem = new javax.swing.JMenuItem();
        loansMenu = new javax.swing.JMenu();
        loansMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BiblioTechKeihlAlvaradoSemestreI2018");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.jpg"))); // NOI18N
        jLabel2.setOpaque(true);

        interfaceMenuBar.setBackground(new java.awt.Color(51, 51, 51));

        systemMenu.setText("Sistema");

        creditsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credits.png"))); // NOI18N
        creditsMenuItem.setText("Créditos");
        creditsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsMenuItemActionPerformed(evt);
            }
        });
        systemMenu.add(creditsMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        systemMenu.add(exitMenuItem);

        interfaceMenuBar.add(systemMenu);

        registryMenu.setText("Registrar");

        materialMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/material.png"))); // NOI18N
        materialMenu.setText("Material");

        bookMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.png"))); // NOI18N
        bookMenuItem.setText("Libro");
        bookMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookMenuItemActionPerformed(evt);
            }
        });
        materialMenu.add(bookMenuItem);

        audioVisualMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/audivisualMaterial.png"))); // NOI18N
        audioVisualMenuItem.setText("Audiovisual");
        audioVisualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioVisualMenuItemActionPerformed(evt);
            }
        });
        materialMenu.add(audioVisualMenuItem);

        registryMenu.add(materialMenu);

        studentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N
        studentMenuItem.setText("Estudiante");
        studentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuItemActionPerformed(evt);
            }
        });
        registryMenu.add(studentMenuItem);

        interfaceMenuBar.add(registryMenu);

        loansMenu.setText("Préstamos");
        loansMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansMenuActionPerformed(evt);
            }
        });

        loansMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loans.png"))); // NOI18N
        loansMenuItem.setText("Solicitar");
        loansMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansMenuItemActionPerformed(evt);
            }
        });
        loansMenu.add(loansMenuItem);

        interfaceMenuBar.add(loansMenu);

        setJMenuBar(interfaceMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Establece la acción del menuItem Salir
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    //Establece la acción del menuItem Créditos
    private void creditsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsMenuItemActionPerformed
        Credits credits = new Credits(this, true);
        credits.setVisible(true);
    }//GEN-LAST:event_creditsMenuItemActionPerformed

    //Establece la acción del menuItem Libros
    private void bookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookMenuItemActionPerformed
        RegisterBook registerBook = new RegisterBook(this, true);
        registerBook.setVisible(true);
    }//GEN-LAST:event_bookMenuItemActionPerformed

    //Establece la acción del menuItem Audiovisual
    private void audioVisualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioVisualMenuItemActionPerformed
        RegisterAudioVisualMaterial registerMaterial = new RegisterAudioVisualMaterial(this, true);
        registerMaterial.setVisible(true);
    }//GEN-LAST:event_audioVisualMenuItemActionPerformed

    //Establece la acción del menu Préstamos
    private void loansMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansMenuActionPerformed
        
    }//GEN-LAST:event_loansMenuActionPerformed

    //Establece la acción del menuItem Estudiante
    private void studentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuItemActionPerformed
        RegisterStudents registerStudents = new RegisterStudents(this, true);
        registerStudents.setVisible(true);
    }//GEN-LAST:event_studentMenuItemActionPerformed

    //Establece la acción del menuItem Solicitar
    private void loansMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansMenuItemActionPerformed
        Loans loans = new Loans(this, true);
        loans.setVisible(true);
    }//GEN-LAST:event_loansMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem audioVisualMenuItem;
    private javax.swing.JMenuItem bookMenuItem;
    private javax.swing.JMenuItem creditsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar interfaceMenuBar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu loansMenu;
    private javax.swing.JMenuItem loansMenuItem;
    private javax.swing.JMenu materialMenu;
    private javax.swing.JMenu registryMenu;
    private javax.swing.JMenuItem studentMenuItem;
    private javax.swing.JMenu systemMenu;
    // End of variables declaration//GEN-END:variables
}
