/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuInterface;

import data.MaterialFile;
import domain.Book;
import domain.Material;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan Keihl
 */
public class RegisterBook extends javax.swing.JDialog {

    /**
     * Creates new form RegisterBook
     */
    public RegisterBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        yesBookLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerBookPanel = new javax.swing.JPanel();
        registerBookLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        formatLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        codeTextField = new javax.swing.JTextField();
        formatComboBox = new javax.swing.JComboBox<>();
        registerButton = new javax.swing.JButton();
        yesBookLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Libro");

        registerBookPanel.setBackground(new java.awt.Color(51, 51, 51));

        registerBookLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerBookLabel.setForeground(new java.awt.Color(0, 102, 204));
        registerBookLabel.setText("Ingrese los datos del libro a registrar:");

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Nombre:");

        authorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorLabel.setText("Autor:");

        yearLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("Año de Publicación:");

        codeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        codeLabel.setForeground(new java.awt.Color(255, 255, 255));
        codeLabel.setText("Código:");

        formatLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        formatLabel.setForeground(new java.awt.Color(255, 255, 255));
        formatLabel.setText("Formato:");

        formatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Físico", "Digital" }));

        registerButton.setText("Registrar");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        yesBookLabel.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        yesBookLabel.setForeground(new java.awt.Color(0, 153, 0));
        yesBookLabel.setText("Libro registrado.");

        javax.swing.GroupLayout registerBookPanelLayout = new javax.swing.GroupLayout(registerBookPanel);
        registerBookPanel.setLayout(registerBookPanelLayout);
        registerBookPanelLayout.setHorizontalGroup(
            registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerBookPanelLayout.createSequentialGroup()
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerBookPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(registerBookLabel))
                    .addGroup(registerBookPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBookPanelLayout.createSequentialGroup()
                                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(authorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField)
                                    .addComponent(authorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerBookPanelLayout.createSequentialGroup()
                                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearLabel)
                                    .addComponent(codeLabel)
                                    .addComponent(formatLabel)
                                    .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yesBookLabel)
                                        .addComponent(registerButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearTextField)
                                    .addComponent(codeTextField)
                                    .addComponent(formatComboBox, 0, 246, Short.MAX_VALUE))))))
                .addGap(56, 56, 56))
        );
        registerBookPanelLayout.setVerticalGroup(
            registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerBookPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(registerBookLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatLabel)
                    .addComponent(formatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yesBookLabel)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Establece la acción del boton registrar
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        try {

            if (nameTextField.getText().equalsIgnoreCase("") || authorTextField.getText().equalsIgnoreCase("")
                    || yearTextField.getText().equalsIgnoreCase("") || codeTextField.getText().equalsIgnoreCase("")
                    || formatComboBox.getSelectedItem().toString().equalsIgnoreCase("--")) {
                throw new NullPointerException();
            }
            
            MaterialFile materialFile = new MaterialFile();
            
            String name = nameTextField.getText();
            String author = authorTextField.getText();
            int year = Integer.parseInt(yearTextField.getText());
            int code = Integer.parseInt(codeTextField.getText());
            String format = formatComboBox.getSelectedItem().toString();
            
            Material material = new Book(name, year, author, code, true, format);
            materialFile.addMaterials(material);
            
            yesBookLabel.setVisible(true);
            
            nameTextField.setText("");
            authorTextField.setText("");
            yearTextField.setText("");
            codeTextField.setText("");
            formatComboBox.setSelectedItem("--");
            
            
            

        } catch (NullPointerException e) {
            yesBookLabel.setVisible(false);
            JOptionPane.showMessageDialog(null, "Espacios en blanco, favor completar.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error 1000 - File can't save book.");
        }


    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterBook dialog = new RegisterBook(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JComboBox<String> formatComboBox;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel registerBookLabel;
    private javax.swing.JPanel registerBookPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JLabel yesBookLabel;
    // End of variables declaration//GEN-END:variables
}
