/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuInterface;

import data.MaterialFile;
import domain.AudioVisualMaterial;
import domain.Material;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan Keihl
 */
public class RegisterAudioVisualMaterial extends javax.swing.JDialog {

    /**
     * Creates new form RegisterAudioVisualMaterial
     */
    public RegisterAudioVisualMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        yesMaterialLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        registerAudioVisualMaterialPanel = new javax.swing.JPanel();
        registerMaterialLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        codeTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        yesMaterialLabel = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Material Audiovisual");
        setLocation(new java.awt.Point(415, 195));

        registerAudioVisualMaterialPanel.setBackground(new java.awt.Color(51, 51, 51));

        registerMaterialLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerMaterialLabel.setForeground(new java.awt.Color(0, 102, 204));
        registerMaterialLabel.setText("Ingrese los datos del material a registrar:");

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Tipo de Material:");

        descriptionLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Descripción:");

        codeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        codeLabel.setForeground(new java.awt.Color(255, 255, 255));
        codeLabel.setText("Código:");

        registerButton.setText("Registrar");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        yesMaterialLabel.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        yesMaterialLabel.setForeground(new java.awt.Color(0, 153, 0));
        yesMaterialLabel.setText("Material registrado.");

        javax.swing.GroupLayout registerAudioVisualMaterialPanelLayout = new javax.swing.GroupLayout(registerAudioVisualMaterialPanel);
        registerAudioVisualMaterialPanel.setLayout(registerAudioVisualMaterialPanelLayout);
        registerAudioVisualMaterialPanelLayout.setHorizontalGroup(
            registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerAudioVisualMaterialPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerMaterialLabel)
                    .addGroup(registerAudioVisualMaterialPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(nameLabel)
                            .addGroup(registerAudioVisualMaterialPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yesMaterialLabel)
                                    .addComponent(registerButton))))
                        .addGap(23, 23, 23)
                        .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descriptionTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(codeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerAudioVisualMaterialPanelLayout.setVerticalGroup(
            registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerAudioVisualMaterialPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(registerMaterialLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerAudioVisualMaterialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yesMaterialLabel)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerAudioVisualMaterialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerAudioVisualMaterialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Establece la acción del boton Registrar
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        try {

            if (nameTextField.getText().equalsIgnoreCase("") || descriptionTextField.getText().equalsIgnoreCase("")
                    || codeTextField.getText().equalsIgnoreCase("")) {

                throw new NullPointerException();

            }

            MaterialFile materialFile = new MaterialFile();

            String name = nameTextField.getText();
            String description = descriptionTextField.getText();
            int code = Integer.parseInt(codeTextField.getText());

            Material material = new AudioVisualMaterial(name, description, code, true);

            materialFile.addMaterials(material);

            yesMaterialLabel.setVisible(true);
            
            nameTextField.setText("");
            descriptionTextField.setText("");
            codeTextField.setText("");
            
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error 1001 - File can't save audivisual material.");
        } catch (NullPointerException e) {
            yesMaterialLabel.setVisible(false);
            JOptionPane.showMessageDialog(null, "Espacios en blanco, favor completar.");
        }


    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAudioVisualMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAudioVisualMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAudioVisualMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAudioVisualMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterAudioVisualMaterial dialog = new RegisterAudioVisualMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel registerAudioVisualMaterialPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerMaterialLabel;
    private javax.swing.JLabel yesMaterialLabel;
    // End of variables declaration//GEN-END:variables
}
